name: Main

on: push

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  readmeWorkflow:
    name: Readme Workflow
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: unity-ci-test/Library
          key: Library-unity-ci-test-WebGL

      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.3
        with:
          projectPath: unity-ci-test
          unityVersion: 2019.2.0f1

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          projectPath: unity-ci-test
          unityVersion: 2019.2.0f1
          targetPlatform: WebGL

      # Output
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
