name: Main

on: push

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  testAndBuild:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v2

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: unity-ci-test/Library
          key: Library-unity-ci-test-StandaloneWindows64

      # Test
      - uses: webbertakken/unity-test-runner@v1.3
        id: testRunner
        with:
          projectPath: unity-ci-test
          unityVersion: 2019.2.0f1

      # Test Output
      - uses: actions/upload-artifact@v1
        with:
          name: Test results
          path: ${{ steps.testRunner.outputs.artifactsPath }}

      # Build
      - uses: webbertakken/unity-builder@v0.12
        with:
          projectPath: unity-ci-test
          unityVersion: 2019.2.0f1
          targetPlatform: StandaloneWindows64

      # Build Output
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
