name: Main

on: push

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  testAndBuild:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.12
        with:
          projectPath: unity-ci-test
          unityVersion: 2019.2.0f1
          targetPlatform: StandaloneWindows64

      # Build Output
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
